### ISSUE TITLE
http codes shazam.js

### ISSUE THREAD

**Issue by FLira2000** [MateusAquino/tweet-music-recognizer#3]
Opa, tudo bom?
Usei seu bot umas vzes no twitter, e resolvi vir aqui dar uma olhada como funciona. É sensacional, adorei o projeto e já dei uma estrela

Queria ser útil da mesma forma que esse bot foi pra mim, e to fazendo umas revisões. É sempre bom revisar código bom, então, fica tranquilo que isso não é bem um erro! 
Mas o fundamento dessa issue é bem mais voltada a comunicação de redes do que em questões de programação e desenvolvimento.

Erros de código HTTP tem seus tipos bem especificados para quando estes estejam trafegando em seus pacotes, os comutadores de rede no caminho farão melhor alocação de recursos na hora de repassar para os próximos, se rede for proativa(Tanenbaum, Redes de Computadores ed. 6, capítulos 2, 3 e 6).

```javascript
} else if (response.data) { // Musica não encontrada
     resolve('404')  
} else { // Outro erro
    console.error('Unexpected error from Shazam API')
    //console.log(response)
    >>>resolve('599')  // HTTP Conection Timeout, mais usado com proxys, mas ainda sim é válido
}
```

**Comment by MateusAquino** [comment]
Oioi! hihi valeu Fábio o/
Os códigos HTTP foram corrigidos na df962f5f94fb48b305b89ac881719614de482d6b.

Agradeço pela correção 😎
