### ISSUE TITLE
How do you add multiple API keys?

### ISSUE THREAD

**Issue by mjsal** [MateusAquino/tweet-music-recognizer#6]
I’m trying to add one more Acr api key in the control panel, however when I close the control panel and open it back the second api key and secret disappears and leaves me only with one key.

**Comment by MateusAquino** [comment]
Hey, Thank you for reaching out!
If you have already setup mongodb correctly, you should be able to add the keys like this:
```
Key1, Secret1, 0
Key2, Secret2, 0
Key3, Secret3, 0
...
```
Once you are done, press the `Save Changes` button.

**Comment by mjsal** [comment]
thank you :)
